In [ ]:
import numpy as np


In [ ]:
strings = np.array(['one', 'two', 'one', 'four', 'two', 'one', 'two', 'three', 'one', 'three'])

strings

array(['one', 'two', 'one', 'four', 'two', 'one', 'two', 'three', 'one',
       'three'], dtype='<U5')

In [ ]:
integers = np.array([[1, 1, 1, 1], 
                     [2, 2, 2, 2], 
                     [3, 3, 3, 3], 
                     [4, 4, 4, 4], 
                     [5, 5, 5, 5], 
                     [6, 6, 6, 6], 
                     [7, 7, 7, 7], 
                     [8, 8, 8, 8], 
                     [9, 9, 9, 9], 
                     [0, 0, 0, 0]])

integers

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9],
       [0, 0, 0, 0]])

In [ ]:
strings == 'one'

array([ True, False,  True, False, False,  True, False, False,  True,
       False])

In [ ]:
integers[strings == 'two']

array([[2, 2, 2, 2],
       [5, 5, 5, 5],
       [7, 7, 7, 7]])

In [ ]:
integers[integers > 7] = 0

integers

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
integers[strings == 'three'] = 9

integers

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [9, 9, 9, 9],
       [0, 0, 0, 0],
       [9, 9, 9, 9]])

In [ ]:
select = (strings == 'one') | (strings == 'four')

select

array([ True, False,  True,  True, False,  True, False, False,  True,
       False])

In [ ]:
integers[~(strings == 'three')]

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [0, 0, 0, 0]])

In [ ]:
int_copy = integers[:6, :2].copy()

int_copy[4, 0] = 12

int_copy

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [12,  5],
       [ 6,  6]])

In [ ]:
grid = np.arange(1, 13).reshape(4, 3)
grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
integers[strings == 'one']

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [6, 6, 6, 6],
       [0, 0, 0, 0]])

In [ ]:
integers[3:]

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [9, 9, 9, 9],
       [0, 0, 0, 0],
       [9, 9, 9, 9]])

In [ ]:
(integers[strings == 'one', 2])[1]


3