Имеется строка, содержащая имена клиентов
C_names=“Barnes Abramson Macduff Johnson Andrews Lewin Brown”
И информация о длительности звонков клиентов в роуминге за каждый
последних 6 месяцев (варьируется от 100 до 350 мин. / мес).

In [ ]:
import numpy as np
C_names = "Barnes Abramson Macduff Johnson Andrews Lewin Brown"
clients = np.array(C_names.split())
clients

array(['Barnes', 'Abramson', 'Macduff', 'Johnson', 'Andrews', 'Lewin',
       'Brown'], dtype='<U8')

1. Сгенерировать NumPy массив (“Customer’s roaming call duration”) ,
содержащий эту информацию, используя подходящий метод модуля random.

In [ ]:
calls = np.random.randint(100, 350, (7, 6))
calls

array([[192, 328, 117, 239, 185, 339],
       [185, 279, 292, 155, 326, 120],
       [338, 116, 274, 127, 302, 348],
       [292, 204, 316, 174, 331, 241],
       [107, 319, 312, 209, 180, 304],
       [272, 248, 175, 283, 167, 308],
       [165, 151, 187, 138, 335, 315]])

2. Выбрать из него (вывести) все строки, содержащие информацию о
клиентах Abramson и Johnson.

In [ ]:
calls[(clients == "Abramson") | (clients == "Johnson")]

array([[185, 279, 292, 155, 326, 120],
       [292, 204, 316, 174, 331, 241]])

3. Выбрать информацию обо всех клиентах, кроме Macduff и Lewin

In [ ]:
calls[(clients != "Macduff") & (clients != "Lewin")]

array([[192, 328, 117, 239, 185, 339],
       [185, 279, 292, 155, 326, 120],
       [292, 204, 316, 174, 331, 241],
       [107, 319, 312, 209, 180, 304],
       [165, 151, 187, 138, 335, 315]])

4. Вывести информацию о клиенте Brown за период 2-4 месяцы

In [ ]:
calls[(clients == "Brown"), 1:4]

array([[151, 187, 138]])

5. Вывести информацию обо всех клиентах, кроме Barnes за нечетные
месяцы.

In [ ]:
calls[(clients != "Barnes"), ::2]

array([[185, 292, 326],
       [338, 274, 302],
       [292, 316, 331],
       [107, 312, 180],
       [272, 175, 167],
       [165, 187, 335]])

6. Стоимость минуты разговора в роуминге составляет 1.6$. Создайте
новый массив NumPy (Customer’s roaming call cost), содержащий информацию
о расходах каждого клиента в определенный месяц (основываясь на данных
из массива “Customer’s roaming call duration”).

In [ ]:
costs = calls * 1.6
costs

array([[307.2, 524.8, 187.2, 382.4, 296. , 542.4],
       [296. , 446.4, 467.2, 248. , 521.6, 192. ],
       [540.8, 185.6, 438.4, 203.2, 483.2, 556.8],
       [467.2, 326.4, 505.6, 278.4, 529.6, 385.6],
       [171.2, 510.4, 499.2, 334.4, 288. , 486.4],
       [435.2, 396.8, 280. , 452.8, 267.2, 492.8],
       [264. , 241.6, 299.2, 220.8, 536. , 504. ]])

7. Курс доллара составляет 28 ₴. Рассчитайте и выведите общие затраты
клиента Andrews в гривнах.

In [ ]:
costs[(clients == "Andrews")] * 28

array([[ 4793.6, 14291.2, 13977.6,  9363.2,  8064. , 13619.2]])

**Сумасшедшие цены**