**Курсовая работа по ЗДМИ (часть 1)**

1. Файл “ratings.csv” зберігає інформацію про клієнтів online-бібліотеки,
книги та оцінки книг читачами: book_id, user_id, rating.

In [ ]:
import numpy as np

In [ ]:
path = "/content/drive/MyDrive/ratings.csv - ratings.csv.csv"

a_from = 120 #@param

a_to = 28341 #@param

n1 = 6 #@param

n2 = 3866 #@param

n4 =  485#@param

n5 =  382#@param

n6 =  430#@param

n7 =  447#@param

m1 = 530 #@param

m2 = 711 #@param

In [ ]:
file_array = np.genfromtxt(path, delimiter=',', dtype='int32', skip_header=1)
len(file_array)

981756

2. Прочитати з файлу відповідну частину стовбця user_id (діапазон строк
задається по варіанту студента, див. Додаток А) у NumPy масив C_id.

In [ ]:
c_id = file_array[a_from:a_to, 1]
c_id

array([11408, 11691, 11692, ..., 13095, 13794, 13879], dtype=int32)

3. Виконати генерацію значень NumPy масиву (CRT – Customer Reading
Time), який зберігає інформацію про кількість хвилин, які витратили
клієнти на читання книг, знаходячись безпосередньо на сайті в режимі
онлайн (за кожен з N1 останніх місяців поточного року у діапазоні від M1
до M2).

In [ ]:
crt = np.random.randint(m1, m2, [len(c_id), n1])
crt

array([[582, 652, 690, 671, 638, 579],
       [647, 576, 582, 694, 628, 696],
       [644, 654, 631, 572, 530, 629],
       ...,
       [650, 683, 545, 535, 602, 613],
       [641, 684, 660, 682, 692, 610],
       [543, 546, 613, 549, 571, 646]])

4. Вивести інформацію щодо кількості хвилин, які витратили клієнти на
читання книг у парні місяці (для парних варіантів студентів) або у непарні
(для непарних варіантів студентів).

In [ ]:
crt[:, 1::2]

array([[652, 671, 579],
       [576, 694, 696],
       [654, 572, 629],
       ...,
       [683, 535, 613],
       [684, 682, 610],
       [546, 549, 646]])

5. Вивести інформацію по першим N2 та останнім N3 клієнтам
набору. N3 згенерувати використовуючи відповідну функцію модулю
random.

In [ ]:
n3 = np.random.randint(len(crt) - n2)
n3

22294

In [ ]:
crt[:n2]

array([[582, 652, 690, 671, 638, 579],
       [647, 576, 582, 694, 628, 696],
       [644, 654, 631, 572, 530, 629],
       ...,
       [635, 646, 705, 650, 588, 564],
       [616, 647, 708, 570, 589, 598],
       [636, 561, 634, 641, 672, 609]])

In [ ]:
crt[n3:]

array([[706, 704, 530, 639, 574, 589],
       [532, 659, 660, 596, 571, 567],
       [658, 674, 703, 598, 560, 626],
       ...,
       [650, 683, 545, 535, 602, 613],
       [641, 684, 660, 682, 692, 610],
       [543, 546, 613, 549, 571, 646]])

6. Вивести інформацію за перші три місяці для клієнта, user_id якого
знаходиться в позиції N4 у C_id.

In [ ]:
crt[c_id == c_id[n4], :3]

array([[669, 658, 636],
       [653, 543, 567],
       [584, 653, 613],
       [645, 654, 698],
       [615, 613, 603],
       [614, 550, 654],
       [703, 634, 632],
       [704, 703, 539],
       [544, 617, 531],
       [674, 628, 654],
       [692, 602, 619],
       [585, 670, 644],
       [577, 546, 568],
       [567, 659, 645],
       [562, 585, 626],
       [597, 534, 565],
       [691, 642, 563],
       [623, 562, 642],
       [632, 575, 597],
       [592, 699, 709],
       [708, 664, 563],
       [688, 607, 577],
       [661, 562, 545],
       [634, 617, 702],
       [634, 621, 667],
       [636, 533, 702],
       [681, 693, 563],
       [609, 672, 534],
       [684, 564, 593],
       [684, 616, 679],
       [600, 593, 597],
       [686, 673, 635],
       [630, 608, 584],
       [655, 616, 557],
       [710, 592, 566],
       [626, 552, 551],
       [613, 666, 699],
       [678, 583, 612],
       [608, 652, 660],
       [689, 643, 532],
       [545, 631, 596],
       [562, 640

7. Використовуючи логічну індексацію вивести інформацію для клієнта з
відповідним user_id (user_id якого знаходиться в позиції N5 у C_id)

In [ ]:
crt[c_id == c_id[n5]]

array([[637, 651, 676, 647, 591, 539],
       [542, 568, 595, 657, 708, 579],
       [561, 588, 593, 694, 701, 554],
       [696, 645, 617, 609, 607, 686],
       [627, 584, 673, 612, 696, 670],
       [656, 609, 580, 570, 651, 552],
       [566, 671, 689, 610, 695, 671],
       [651, 641, 647, 542, 710, 685],
       [673, 669, 603, 635, 703, 699],
       [701, 611, 582, 697, 680, 656],
       [699, 571, 662, 652, 533, 622],
       [596, 582, 605, 684, 542, 573],
       [544, 641, 677, 690, 643, 605],
       [683, 705, 557, 635, 562, 576],
       [533, 646, 615, 710, 536, 582],
       [610, 697, 644, 693, 666, 582],
       [540, 631, 683, 573, 590, 666],
       [564, 630, 684, 596, 607, 696],
       [576, 667, 558, 566, 661, 567],
       [590, 683, 667, 540, 640, 625],
       [562, 568, 602, 609, 643, 632],
       [581, 606, 633, 541, 610, 604],
       [532, 703, 649, 566, 587, 659],
       [636, 675, 592, 532, 676, 590],
       [638, 640, 606, 549, 653, 543],
       [648, 554, 676, 63

8. Для даного читача вивести інформацію за останні 2 місяця.

In [ ]:
crt[c_id == c_id[n5], -2:]

array([[591, 539],
       [708, 579],
       [701, 554],
       [607, 686],
       [696, 670],
       [651, 552],
       [695, 671],
       [710, 685],
       [703, 699],
       [680, 656],
       [533, 622],
       [542, 573],
       [643, 605],
       [562, 576],
       [536, 582],
       [666, 582],
       [590, 666],
       [607, 696],
       [661, 567],
       [640, 625],
       [643, 632],
       [610, 604],
       [587, 659],
       [676, 590],
       [653, 543],
       [604, 623],
       [549, 666],
       [587, 620],
       [642, 558],
       [605, 652],
       [602, 642],
       [547, 701],
       [650, 634],
       [654, 704],
       [590, 569],
       [602, 549],
       [623, 626],
       [639, 684],
       [639, 698],
       [647, 568],
       [584, 552],
       [603, 683],
       [541, 623],
       [570, 595]])

9. Використовуючи логічну індексацію вивести інформацію для клієнтів з
user_id, відмінних від тих, що в позиціях N6, N7 у C_id.

In [ ]:
crt[(c_id != c_id[n6]) & (c_id != c_id[n7])]

array([[582, 652, 690, 671, 638, 579],
       [647, 576, 582, 694, 628, 696],
       [644, 654, 631, 572, 530, 629],
       ...,
       [650, 683, 545, 535, 602, 613],
       [641, 684, 660, 682, 692, 610],
       [543, 546, 613, 549, 571, 646]])

10. Прочитати з файлу частину стовбця book_id відповідно до частини
user_id, сформувати NumPy масив В_id. Для кожної книги з В_id на основі
даних з CRT розрахувати загальну кількість хвилин, яку на неї витратили
клієнти у першому місяці.

In [ ]:
b_id = file_array[a_from:a_to, 0]
b_id

array([  2,   2,   2, ..., 284, 284, 284], dtype=int32)

In [ ]:
uniq_b_id = np.unique(b_id) 
uniq_b_id

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [ ]:
length = len(uniq_b_id)
minutes = np.zeros(length, dtype="int32")
for i in range(length):
  minutes[i] = np.sum(crt[b_id == uniq_b_id[i], 0])

minutes

array([49858, 61715, 62497, 61676, 61602, 62285, 61480, 61632, 61151,
       62054, 61475, 62949, 61756, 60852, 61396, 62339, 62529, 62147,
       62223, 61461, 61725, 61518, 62211, 62083, 62293, 62350, 63000,
       62118, 61368, 62247, 61868, 61899, 62456, 61794, 61776, 62495,
       61737, 61509, 61828, 61334, 61903, 63071, 61044, 61729, 62299,
       62110, 62089, 62960, 62521, 61593, 61866, 62291, 61193, 61532,
       62434, 61823, 62058, 61896, 61758, 62940, 61522, 61671, 61605,
       61330, 61287, 61783, 62379, 62365, 61291, 62441, 61705, 62395,
       61548, 62324, 62034, 62240, 62220, 61737, 62295, 61965, 61814,
       62013, 61961, 61512, 61688, 62437, 62058, 62084, 62474, 62055,
       62782, 62510, 62488, 61989, 61687, 62386, 61987, 62276, 61597,
       62280, 62391, 61790, 62068, 62196, 62124, 62128, 62063, 61205,
       61101, 62153, 62192, 61528, 62645, 61895, 60755, 61894, 62236,
       62298, 62027, 62142, 62664, 61210, 62342, 62235, 61545, 62216,
       62209, 61356,

11. Вивести загальну кількість хвилин, що було затрачено
всіма клієнтами на читання книги з порядковим номером N8 (N8= No варіанту*5+No
варіанту) у масиві В_id.

In [ ]:
n8 = 24

booksum = np.sum(crt[b_id == b_id[n8]])

booksum

298137