In [2]:
import numpy as np

Перший регіон.

Кожен рядок даних по першому регіону відповідає місту регіону.

Кожен стовбець даних по першому регіону відповідає місяцю 2018 року
(в діапазоні по варіанту).

In [3]:
Nikolaev_rows = 12
Nikolaev_columns = 3 #3-5
Nikolaev_min = 85
Nikolaev_max = 160

Другий регіон.

Кожен рядок даних по першому регіону відповідає місяцю 2018 року (10
місяців)

Кожен стовбець даних по другому регіону відповідає кількості міст
регіону+20

In [4]:
Odessa_rows = 10
Odessa_columns = 32
Odessa_min = 100
Odessa_max = 250

1. Згенерувати два ndarray (матриці) по заданим регіонам, відповідно заданої
у описі предметної області структурі та відповідної розмірності. Комірки
матриць зберігають тривалості дзвінків абонентів у роумінгу

In [5]:
Odessa = np.random.randint(Odessa_min, Odessa_max, size=[Odessa_rows, Odessa_columns])
Odessa

array([[147, 116, 124, 249, 131, 212, 239, 227, 213, 133, 109, 151, 189,
        119, 206, 167, 112, 249, 114, 237, 129, 218, 166, 165, 109, 116,
        212, 162, 217, 150, 165, 201],
       [148, 222, 174, 225, 242, 105, 232, 118, 200, 142, 113, 200, 184,
        248, 232, 103, 181, 120, 170, 143, 155, 248, 190, 162, 115, 188,
        236, 102, 200, 247, 228, 133],
       [200, 166, 182, 214, 218, 103, 222, 220, 212, 155, 195, 182, 135,
        243, 122, 140, 233, 192, 181, 190, 199, 204, 117, 209, 219, 200,
        167, 166, 122, 169, 100, 190],
       [205, 214, 209, 223, 225, 155, 240, 196, 160, 111, 101, 242, 231,
        173, 125, 241, 157, 143, 239, 179, 162, 234, 168, 132, 160, 196,
        184, 105, 228, 149, 233, 141],
       [135, 185, 230, 240, 202, 226, 114, 105, 140, 131, 193, 119, 183,
        188, 105, 171, 187, 185, 191, 196, 203, 190, 211, 165, 155, 206,
        227, 150, 138, 119, 117, 234],
       [118, 124, 105, 156, 127, 232, 141, 157, 194, 118, 166, 191, 145,
  

In [6]:
Nikolaev = np.random.randint(Nikolaev_min, Nikolaev_max, size=[Nikolaev_rows, Nikolaev_columns])
Nikolaev

array([[109, 146, 155],
       [142, 123, 157],
       [120, 113, 142],
       [107, 149, 158],
       [143, 124, 145],
       [112, 131, 133],
       [123,  96,  95],
       [102, 138, 108],
       [124, 140, 127],
       [ 97,  97,  99],
       [108, 143, 122],
       [150, 106, 131]])

2. Створити новий (загальний) ndarray для зберігання всієї інформації з двох
заданих регіонів за вказаний в таблиці Б.3 діапазон місяців, виконавши
операції зрізу, трансформації (рядки нової матриці - міста, стовпці - місяці)
і операції об'єднання.

**В варианте 3-4, но в Николаеве их всего 3, поэтому я взял 2-3**

In [7]:
a1 = Nikolaev[:, 1:3]

a1

array([[146, 155],
       [123, 157],
       [113, 142],
       [149, 158],
       [124, 145],
       [131, 133],
       [ 96,  95],
       [138, 108],
       [140, 127],
       [ 97,  99],
       [143, 122],
       [106, 131]])

In [8]:
a2 = Odessa[1:3, :].transpose()

a2

array([[148, 200],
       [222, 166],
       [174, 182],
       [225, 214],
       [242, 218],
       [105, 103],
       [232, 222],
       [118, 220],
       [200, 212],
       [142, 155],
       [113, 195],
       [200, 182],
       [184, 135],
       [248, 243],
       [232, 122],
       [103, 140],
       [181, 233],
       [120, 192],
       [170, 181],
       [143, 190],
       [155, 199],
       [248, 204],
       [190, 117],
       [162, 209],
       [115, 219],
       [188, 200],
       [236, 167],
       [102, 166],
       [200, 122],
       [247, 169],
       [228, 100],
       [133, 190]])

In [9]:
a12 = np.concatenate((a1, a2))

a12

array([[146, 155],
       [123, 157],
       [113, 142],
       [149, 158],
       [124, 145],
       [131, 133],
       [ 96,  95],
       [138, 108],
       [140, 127],
       [ 97,  99],
       [143, 122],
       [106, 131],
       [148, 200],
       [222, 166],
       [174, 182],
       [225, 214],
       [242, 218],
       [105, 103],
       [232, 222],
       [118, 220],
       [200, 212],
       [142, 155],
       [113, 195],
       [200, 182],
       [184, 135],
       [248, 243],
       [232, 122],
       [103, 140],
       [181, 233],
       [120, 192],
       [170, 181],
       [143, 190],
       [155, 199],
       [248, 204],
       [190, 117],
       [162, 209],
       [115, 219],
       [188, 200],
       [236, 167],
       [102, 166],
       [200, 122],
       [247, 169],
       [228, 100],
       [133, 190]])

3. Розрахувати сумарну, максимальну та мінімальну тривалості дзвінків для
кожного місяця і середню кількість дзвінків по кожному місту.

In [10]:
a12.sum(axis = 0)

array([7212, 7339])

In [11]:
a12.max(axis = 0)

array([248, 243])

In [12]:
a12.min(axis = 0)

array([96, 95])

In [13]:
a12.mean(axis = 1)

array([150.5, 140. , 127.5, 153.5, 134.5, 132. ,  95.5, 123. , 133.5,
        98. , 132.5, 118.5, 174. , 194. , 178. , 219.5, 230. , 104. ,
       227. , 169. , 206. , 148.5, 154. , 191. , 159.5, 245.5, 177. ,
       121.5, 207. , 156. , 175.5, 166.5, 177. , 226. , 153.5, 185.5,
       167. , 194. , 201.5, 134. , 161. , 208. , 164. , 161.5])

4. Розрахувати загальну (сумарну) тривалість дзвінків за три останніх місяці
зазначеного в таблиці Б.3 діапазону по всьому набору даних.

**Их всего 2**

In [14]:
a12.sum()

14551

5. Припустимо, що ви отримали 10 окремих рядків, які зберігають
інформацію по 10 новим містам за всі місяці 2017 року і минулі місяці 2018
(січень - жовтень) - 22 значення в кожному отриманому рядку. Діапазон
тривалості дзвінків 85-430 хв.

In [15]:
Newcities = np.random.randint(85, 430, [10, 22])
Newcities

array([[255, 211, 121, 407, 257, 200, 115, 343, 419, 331, 269, 318, 167,
        162, 419, 146, 102, 412, 113, 282, 314, 249],
       [355, 413, 189, 399,  99,  97, 182, 365, 265, 171, 126, 258, 365,
        309, 384, 335, 131, 387, 247, 165, 233, 122],
       [376, 128, 289, 193, 271, 254, 383, 138, 325, 145, 156, 178, 175,
        421, 119, 209, 205, 383, 259, 293, 391,  94],
       [265, 162,  85, 186,  87, 422, 190, 197, 417, 340, 307, 411, 293,
        350, 413, 157, 425, 222, 207, 252, 198, 119],
       [240, 326, 120, 359, 186, 332, 265, 414, 178, 275, 176, 409, 171,
        316, 182, 353, 186, 239, 322, 132,  85, 341],
       [361, 302, 253, 407, 355, 273, 321, 427, 157, 341, 210, 272, 164,
        271, 328, 332,  97,  94, 281, 197, 147, 153],
       [283, 392, 352,  95, 339, 371, 153, 340, 378, 356, 276, 273, 333,
        223, 119, 255, 100, 366, 354,  88, 219,  93],
       [101, 424, 158,  91, 175, 198, 329, 132, 170, 357, 361, 324, 159,
        371, 142, 272, 193, 100, 423, 

6. Додайте нову інформацію в набір, вибравши інформацію тільки за ті місяці,
які вам необхідні (таблиця Б.3)

In [16]:
a3 = Newcities[:, 13:15]
a3

array([[162, 419],
       [309, 384],
       [421, 119],
       [350, 413],
       [316, 182],
       [271, 328],
       [223, 119],
       [371, 142],
       [189, 113],
       [233, 237]])

In [17]:
a123 = np.concatenate((a12, a3))
a123

array([[146, 155],
       [123, 157],
       [113, 142],
       [149, 158],
       [124, 145],
       [131, 133],
       [ 96,  95],
       [138, 108],
       [140, 127],
       [ 97,  99],
       [143, 122],
       [106, 131],
       [148, 200],
       [222, 166],
       [174, 182],
       [225, 214],
       [242, 218],
       [105, 103],
       [232, 222],
       [118, 220],
       [200, 212],
       [142, 155],
       [113, 195],
       [200, 182],
       [184, 135],
       [248, 243],
       [232, 122],
       [103, 140],
       [181, 233],
       [120, 192],
       [170, 181],
       [143, 190],
       [155, 199],
       [248, 204],
       [190, 117],
       [162, 209],
       [115, 219],
       [188, 200],
       [236, 167],
       [102, 166],
       [200, 122],
       [247, 169],
       [228, 100],
       [133, 190],
       [162, 419],
       [309, 384],
       [421, 119],
       [350, 413],
       [316, 182],
       [271, 328],
       [223, 119],
       [371, 142],
       [189,

7. Використовуючи універсальні функції, вивести максимальну та мінімальну
тривалості дзвінків по кожному місту.

In [18]:
a123.max(axis=1)

array([155, 157, 142, 158, 145, 133,  96, 138, 140,  99, 143, 131, 200,
       222, 182, 225, 242, 105, 232, 220, 212, 155, 195, 200, 184, 248,
       232, 140, 233, 192, 181, 190, 199, 248, 190, 209, 219, 200, 236,
       166, 200, 247, 228, 190, 419, 384, 421, 413, 316, 328, 223, 371,
       189, 237])

In [19]:
a123.min(axis=1)

array([146, 123, 113, 149, 124, 131,  95, 108, 127,  97, 122, 106, 148,
       166, 174, 214, 218, 103, 222, 118, 200, 142, 113, 182, 135, 243,
       122, 103, 181, 120, 170, 143, 155, 204, 117, 162, 115, 188, 167,
       102, 122, 169, 100, 133, 162, 309, 119, 350, 182, 271, 119, 142,
       113, 233])

8. За кожний місяць сформувати твердження: «В середньому в місяці Х
тривалість дзвінків в роумінгу становила Y плюс \ мінус Z хвилин». Y і Z
визначити за допомогою відповідних універсальних функцій. Х - номер
місяця (від 1 до 12), а не номер стовпчика.

In [20]:
for X in range(2, 4):
  Y = a123[:, X-2].mean()
  Z = np.std(a123[X-2])
  print(f"В середньому в місяці {X} тривалість дзвінків в роумінгу становила {Y} плюс \ мінус {Z} хвилин")

В середньому в місяці 2 тривалість дзвінків в роумінгу становила 186.24074074074073 плюс \ мінус 4.5 хвилин
В середньому в місяці 3 тривалість дзвінків в роумінгу становила 181.38888888888889 плюс \ мінус 17.0 хвилин
